title: Looking Forward To
description: Interested in Algorithm, Web Development, Machine-Learning

url: http://kim-hyunjo.github.io/looking-forward-to
baseurl: /looking-forward-to
paginate_path: "looking-forward-to/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: Kim-Hyunjo
  email: tulip23@naver.com
  linkedin: Hyunjo

google_analytics: ""

disqus:
    shortname: Hyunjo
